services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - task_data:/app/backend/data

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  task_data:
    driver: local
